### ISSUE TITLE
docker compose

### ISSUE THREAD

**Issue by pavelthq** [andrewmclagan/laravel-hhvm-docker#1]
Console says that: `load_balancer` is invalid name for docker-compose.

**Comment by andrewmclagan** [comment]
Can you please give me more details about the specific error? thank you ;-)

**Comment by pavelthq** [comment]
When I use latest docker-compose It outputs an error. Will check later again

**Comment by andrewmclagan** [comment]
okay thanks, could be an issue with the new docker-compose 1.10 syntax. This is untested.

**Comment by andrewmclagan** [comment]
will put a hold on this issue, going to test with docker v2 syntax in a week

**Comment by andrewmclagan** [comment]
docker-compose syntax coming soon.
