### ISSUE TITLE
how do i run this with laravel?

### ISSUE THREAD

**Issue by g0ld3lux** [andrewmclagan/laravel-hhvm-docker#10]

**Comment by g0ld3lux** [comment]
i try to build it from your repo by cloning it...
do some tweak

```
b99f3c2 added volume of laravel project one folder above this repo
8d15505 change root to /var/www/laravel/public
78d6ce1 change timezone to Asia/Manila
e5ececc removed COPY index.php
05f40eb deleted index.php
18cd02d change virtual host
```

So now the Folder Structure is like so

Laravel
- Docker

in the docker is where your repo is located...

**Comment by andrewmclagan** [comment]
This has been deprecated in place of andrewmclagan/aphex.

just FYI `/var/www` is the dir
