### ISSUE TITLE
Initial build fails on mac

### ISSUE THREAD

**Issue by mattglover11** [andrewmclagan/laravel-hhvm-docker#3]
Get:12 http://httpredir.debian.org jessie/main amd64 Packages [9034 kB]
Fetched 9694 kB in 12s (791 kB/s)
W: GPG error: http://dl.hhvm.com jessie InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5A16E7281BE7A449
W: Failed to fetch http://nginx.org/packages/mainline/debian/dists/jessie/Release  Unable to find expected entry 'RUN/binary-amd64/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c apt-get update && apt-get install -my   supervisor  hhvm    ca-certificates     nginx=${NGINX_VERSION}  nginx-module-xslt   nginx-module-geoip  nginx-module-image-filter   gettext-base    libmcrypt-dev   git     wget    curl    mailutils   sendmail    && docker-php-ext-install mcrypt mbstring     && apt-get clean' returned a non-zero code: 100

**Comment by medaqueno** [comment]
+1

**Comment by andrewmclagan** [comment]
Looking into it.

**Comment by andrewmclagan** [comment]
As i believe that was an upstream issue with the key server. Try again it should be resolved.
