### ISSUE TITLE
[feature] Add custom configs in nginx.conf

### ISSUE THREAD

**Issue by medaqueno** [andrewmclagan/laravel-hhvm-docker#4]
Really great work with this docker image.

I think it could be a useful improvement including these lines at the end of nginx.conf in order to have the option of changing easily config values of Nginx or add virtual host if required.

```
include /etc/nginx/conf.d/*.conf;
include /etc/nginx/sites-enabled/*;
```

Then would be an option for each one to map this folder or not using docker-compose.yml for example.

Thank you.

**Comment by andrewmclagan** [comment]
sure, good idea. could you make a PR and i will merge it
