### ISSUE TITLE
unknown log format "compression" in /etc/nginx/nginx.conf:34

### ISSUE THREAD

**Issue by sebestenyb** [andrewmclagan/laravel-hhvm-docker#5]
Hi Andrew,

I experience an error as in the subject with nginx.

**Comment by sebestenyb** [comment]
Ah, fixed, cheers :+1:

**Comment by andrewmclagan** [comment]
apologies was a corrupted dockerfile

**Comment by andrewmclagan** [comment]
more updates coming soon.
