### ISSUE TITLE
503 Service unavailable

### ISSUE THREAD

**Issue by terminatur** [andrewmclagan/laravel-hhvm-docker#8]
I have followed your steps exactly, but I am running into "503 Service Unavailable: No server is available to handle this request."

I have attempted to run this locally on a windows and mac system.

**Comment by andrewmclagan** [comment]
Sorry will need more details then a 503 response. 

That means the request is reaching Nginx at least. My assumption is you did not update the hosts file on your system so Nginx does not know where to direct the request.

If you could paste your hosts file here..?

**Comment by andrewmclagan** [comment]
closing this issue, feel free to reopen if you can create a reproducible error.
