### ISSUE TITLE
commit messages could be better

### ISSUE THREAD

**Issue by gardner** [andrewmclagan/laravel-hhvm-docker#9]
Just noticed that you may want to improve the content of the commit messages. These don't instill faith:

<img width="377" alt="screen shot 2016-10-21 at 4 15 59 pm" src="https://cloud.githubusercontent.com/assets/787026/19611953/a6578ba2-97a9-11e6-97b2-b58e5639e46b.png">

**Comment by andrewmclagan** [comment]
hah... yes apologies did not realise this repo was receiving so much traction. It was more internal then external, point noted. 

Also to follow on we are deprecating this in favour of an Alpine linux base and php-fpm / unix socket implementation.
